-- Run this script in Supabase SQL Editor

create extension if not exists pgcrypto;

-- Core catalog
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  game text not null,
  subcategory text not null,
  title text not null,
  description text not null default '',
  price numeric(10,2) not null check (price >= 0),
  featured boolean not null default false,
  hue integer not null default 180,
  code text not null default 'TC',
  image text,
  created_at timestamptz not null default now()
);

-- User cart persisted in cloud
create table if not exists public.cart_items (
  user_id uuid not null references auth.users(id) on delete cascade,
  product_id bigint not null references public.products(id) on delete cascade,
  quantity integer not null check (quantity > 0),
  updated_at timestamptz not null default now(),
  primary key (user_id, product_id)
);

-- Checkout orders
create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  order_number text not null unique,
  customer_name text not null,
  customer_email text not null,
  customer_country text not null,
  subtotal numeric(10,2) not null check (subtotal >= 0),
  shipping numeric(10,2) not null check (shipping >= 0),
  tax numeric(10,2) not null check (tax >= 0),
  total numeric(10,2) not null check (total >= 0),
  status text not null default 'confirmed' check (status in ('confirmed', 'processing', 'completed', 'canceled')),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated always as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id) on delete set null,
  product_title text not null,
  unit_price numeric(10,2) not null check (unit_price >= 0),
  quantity integer not null check (quantity > 0),
  line_total numeric(10,2) not null check (line_total >= 0),
  created_at timestamptz not null default now()
);

-- Support chat history
create table if not exists public.chat_messages (
  id bigint generated always as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null check (role in ('user', 'bot')),
  message text not null,
  created_at timestamptz not null default now()
);

-- Booster recruitment form
create table if not exists public.booster_applications (
  id bigint generated always as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  full_name text not null,
  email text not null,
  discord text not null,
  game text not null,
  rank text not null,
  weekly_hours integer not null check (weekly_hours between 1 and 168),
  experience text not null,
  status text not null default 'new' check (status in ('new', 'reviewing', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

-- Checkout RPC to prevent client-side total manipulation
create or replace function public.create_order_from_cart(
  p_customer_name text,
  p_customer_email text,
  p_customer_country text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_order_id uuid;
  v_order_number text;
  v_subtotal numeric(10,2);
  v_shipping numeric(10,2);
  v_tax numeric(10,2);
  v_total numeric(10,2);
begin
  if v_user_id is null then
    raise exception 'not_authenticated';
  end if;

  if coalesce(trim(p_customer_name), '') = ''
    or coalesce(trim(p_customer_email), '') = ''
    or coalesce(trim(p_customer_country), '') = '' then
    raise exception 'invalid_customer_data';
  end if;

  select coalesce(sum(p.price * c.quantity), 0)::numeric(10,2)
    into v_subtotal
  from public.cart_items c
  join public.products p on p.id = c.product_id
  where c.user_id = v_user_id;

  if v_subtotal <= 0 then
    raise exception 'empty_cart';
  end if;

  v_shipping := case when v_subtotal >= 120 then 0 else 12 end;
  v_tax := round(v_subtotal * 0.08, 2);
  v_total := round(v_subtotal + v_shipping + v_tax, 2);
  v_order_number := 'TC-' || to_char(now(), 'YYMMDD') || '-' || substr(gen_random_uuid()::text, 1, 6);

  insert into public.orders (
    user_id,
    order_number,
    customer_name,
    customer_email,
    customer_country,
    subtotal,
    shipping,
    tax,
    total,
    status
  ) values (
    v_user_id,
    v_order_number,
    trim(p_customer_name),
    trim(p_customer_email),
    trim(p_customer_country),
    v_subtotal,
    v_shipping,
    v_tax,
    v_total,
    'confirmed'
  ) returning id into v_order_id;

  insert into public.order_items (
    order_id,
    product_id,
    product_title,
    unit_price,
    quantity,
    line_total
  )
  select
    v_order_id,
    p.id,
    p.title,
    p.price,
    c.quantity,
    round(p.price * c.quantity, 2)
  from public.cart_items c
  join public.products p on p.id = c.product_id
  where c.user_id = v_user_id;

  delete from public.cart_items where user_id = v_user_id;

  return jsonb_build_object(
    'order_id', v_order_id,
    'order_number', v_order_number,
    'total', v_total
  );
end;
$$;

grant execute on function public.create_order_from_cart(text, text, text) to authenticated;

alter table public.products enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.chat_messages enable row level security;
alter table public.booster_applications enable row level security;

-- Products are public read
 drop policy if exists "public read products" on public.products;
create policy "public read products"
on public.products for select
to anon, authenticated
using (true);

-- Cart
 drop policy if exists "users manage own cart" on public.cart_items;
create policy "users manage own cart"
on public.cart_items for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Orders
 drop policy if exists "users read own orders" on public.orders;
create policy "users read own orders"
on public.orders for select
to authenticated
using (auth.uid() = user_id);

-- Order items (read only by owner)
 drop policy if exists "users read own order items" on public.order_items;
create policy "users read own order items"
on public.order_items for select
to authenticated
using (
  exists (
    select 1
    from public.orders o
    where o.id = order_id
      and o.user_id = auth.uid()
  )
);

-- Chat
 drop policy if exists "users manage own chat" on public.chat_messages;
create policy "users manage own chat"
on public.chat_messages for all
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

-- Booster applications: allow insert for anon/auth, read own data for authenticated users
 drop policy if exists "anyone submit booster application" on public.booster_applications;
create policy "anyone submit booster application"
on public.booster_applications for insert
to anon, authenticated
with check (true);

 drop policy if exists "users read own booster applications" on public.booster_applications;
create policy "users read own booster applications"
on public.booster_applications for select
to authenticated
using (auth.uid() = user_id);

-- Seed products
alter table public.products alter column id set generated by default;

insert into public.products (id, game, subcategory, title, price, featured, hue, code, image, description)
values
  (301, 'call-of-duty', 'rank-boost', 'COD Rank Boost - Basic', 99, true, 208, 'CO', 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1938090/capsule_616x353.jpg', 'Entry-level ranked progression for solo queue players.'),
  (302, 'call-of-duty', 'camo-unlock', 'COD Camo Unlock - Standard', 149, true, 178, 'CO', 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1938090/capsule_616x353.jpg', 'Fast camo unlock support with progress updates.'),
  (303, 'call-of-duty', 'prestige-leveling', 'COD Prestige Leveling - Advanced', 249, false, 224, 'CO', 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1938090/capsule_616x353.jpg', 'High-volume leveling package for competitive profiles.'),
  (305, 'marvel-rivals', 'rank-boost', 'Marvel Rivals Rank Boost - Basic', 89, true, 330, 'MR', 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2767030/capsule_616x353.jpg', 'Efficient rank climb by verified high-elo players.'),
  (306, 'marvel-rivals', 'rank-boost', 'Marvel Rivals Rank Boost - Pro', 179, false, 336, 'MR', 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2767030/capsule_616x353.jpg', 'Higher volume package for ambitious rank goals.'),
  (307, 'marvel-rivals', 'camo-unlock', 'Marvel Rivals Skin Unlock Service', 119, false, 318, 'MR', 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/2767030/capsule_616x353.jpg', 'Unlock selected cosmetics and event assets safely.'),
  (309, 'battlefield', 'rank-boost', 'Battlefield Rank Boost - Standard', 109, true, 112, 'BF', 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1517290/capsule_616x353.jpg', 'Steady rank progression with account safety protocols.'),
  (310, 'battlefield', 'rank-boost', 'Battlefield Placement Matches Service', 79, false, 116, 'BF', 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1517290/capsule_616x353.jpg', 'Placement optimization by experienced FPS players.'),
  (311, 'battlefield', 'special-items', 'Battlefield Challenge Completion Pack', 129, false, 124, 'BF', 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1517290/capsule_616x353.jpg', 'Objective-driven completion for difficult challenge sets.'),
  (312, 'battlefield', 'service-fee', 'Priority Queue Add-on', 19, false, 132, 'BF', 'https://shared.cloudflare.steamstatic.com/store_item_assets/steam/apps/1517290/capsule_616x353.jpg', 'Move your order to priority allocation for faster start.')
on conflict (id) do update
set
  game = excluded.game,
  subcategory = excluded.subcategory,
  title = excluded.title,
  description = excluded.description,
  price = excluded.price,
  featured = excluded.featured,
  hue = excluded.hue,
  code = excluded.code,
  image = excluded.image;
